"""
LAMBADA SLM Evaluation Dashboard
=================================
Streamlit dashboard for evaluating and comparing three Small Language Models
(Phi-3 Mini, Gemma 2 9B, Llama 3.1 8B) on the LAMBADA benchmark via OpenRouter API.

Run:  streamlit run app.py
"""

import streamlit as st
import streamlit.components.v1 as components
import json
import os
import time
import random
import requests
import base64
import urllib.parse
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from datetime import datetime

# ============================================================================
# Page config
# ============================================================================
st.set_page_config(
    page_title="LAMBADA SLM Evaluation",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ============================================================================
# Model Registry
# ============================================================================
MODELS = {
    "phi-3-mini": {
        "id": "microsoft/phi-3-mini-128k-instruct",
        "name": "Phi-3 Mini",
        "provider": "Microsoft",
        "params": "3.8B",
        "context_window": "128K",
        "architecture": "Dense Transformer Decoder",
        "color": "#2196F3",
    },
    "gemma-2-9b": {
        "id": "google/gemma-2-9b-it:free",
        "name": "Gemma 2 9B",
        "provider": "Google DeepMind",
        "params": "9B",
        "context_window": "8K",
        "architecture": "Transformer Decoder with Local+Global Attention",
        "color": "#4CAF50",
    },
    "llama-3.1-8b": {
        "id": "meta-llama/llama-3.1-8b-instruct:free",
        "name": "Llama 3.1 8B",
        "provider": "Meta",
        "params": "8B",
        "context_window": "128K",
        "architecture": "Dense Transformer Decoder with GQA",
        "color": "#FF9800",
    },
}

MODEL_KEYS = list(MODELS.keys())
MODEL_NAMES = {k: v["name"] for k, v in MODELS.items()}

# ============================================================================
# LLM Detailed Descriptions
# ============================================================================
LLM_DETAILS = {
    "phi-3-mini": {
        "title": "Phi-3 Mini (3.8B) — Microsoft",
        "overview": (
            "Phi-3 Mini is Microsoft's compact 3.8-billion-parameter language model "
            "designed to punch above its weight. It demonstrates that carefully curated, "
            "high-quality training data can outperform brute-force scaling."
        ),
        "working_principle": """
**Architecture:**
- Dense transformer decoder with 32 layers, 3072 hidden dimension, and 32 attention heads
- Grouped-Query Attention (GQA) with 8 KV heads for efficient inference
- RoPE (Rotary Positional Embeddings) supporting a 128K token context window
- SwiGLU activation function and RMSNorm layer normalization

**Training Strategy:**
- Trained primarily on synthetic "textbook-quality" data generated by larger models
- Uses a curriculum learning approach — data is presented in increasing complexity
- The training corpus emphasizes reasoning, math, and code quality over sheer volume
- Instruction-tuned via Supervised Fine-Tuning (SFT) + Direct Preference Optimization (DPO)

**Key Innovation:**
The Phi-3 family proves the *"data quality > data quantity"* hypothesis. By training on 
~3.3T tokens of heavily filtered and synthetic data, Phi-3 Mini achieves performance 
comparable to models 3–5× its size on many benchmarks.

**Strengths for LAMBADA:**
- Strong reading comprehension from textbook-quality training
- Efficient inference with GQA makes it fast for per-passage prediction
- 128K context window easily accommodates long LAMBADA passages
        """,
        "key_specs": {
            "Parameters": "3.8B",
            "Layers": "32",
            "Hidden Size": "3072",
            "Attention Heads": "32 (8 KV)",
            "Context Window": "128K tokens",
            "Vocabulary": "32,064 tokens",
            "Training Data": "~3.3T tokens",
            "Activation": "SwiGLU",
            "Normalization": "RMSNorm",
            "Positional Encoding": "RoPE",
        },
    },
    "gemma-2-9b": {
        "title": "Gemma 2 9B — Google DeepMind",
        "overview": (
            "Gemma 2 9B is Google DeepMind's open-weight model that uses knowledge "
            "distillation from larger Gemma models, achieving remarkable efficiency. "
            "It introduces alternating local/global attention and logit soft-capping."
        ),
        "working_principle": """
**Architecture:**
- Transformer decoder with 42 layers, 3584 hidden dimension, and 16 attention heads
- Alternating sliding-window (local, 4096 tokens) and full (global) attention layers
- Logit soft-capping in attention (50.0) and final layer (30.0) for training stability
- GeGLU activation function and RMSNorm with per-embedding scaling

**Training Strategy:**
- Trained on ~8T tokens of web data, code, and curated text
- Uses knowledge distillation — the 9B model is trained to match the output distribution 
  of the larger 27B Gemma model, capturing richer representations
- Post-training includes SFT on instruction-following data and RLHF with a reward model

**Key Innovation:**
Gemma 2 introduces *alternating attention patterns*: even layers use local sliding-window 
attention (efficient for long sequences), while odd layers use full global attention 
(captures long-range dependencies). Combined with knowledge distillation, this yields 
a 9B model that rivals larger 13B-class competitors.

**Strengths for LAMBADA:**
- Alternating local/global attention naturally handles LAMBADA's long-range dependencies
- Knowledge distillation gives it "knowledge" beyond what 9B parameters normally capture
- GeGLU activation provides smoother gradient flow for nuanced predictions
        """,
        "key_specs": {
            "Parameters": "9B",
            "Layers": "42",
            "Hidden Size": "3584",
            "Attention Heads": "16 (8 KV)",
            "Context Window": "8K tokens",
            "Vocabulary": "256,000 tokens",
            "Training Data": "~8T tokens",
            "Activation": "GeGLU",
            "Normalization": "RMSNorm",
            "Positional Encoding": "RoPE",
        },
    },
    "llama-3.1-8b": {
        "title": "Llama 3.1 8B — Meta",
        "overview": (
            "Llama 3.1 8B is Meta's flagship open-source small model, trained on over "
            "15 trillion tokens. It excels across general NLP tasks and features an "
            "extended 128K context window with optimized Grouped-Query Attention."
        ),
        "working_principle": """
**Architecture:**
- Dense transformer decoder with 32 layers, 4096 hidden dimension, and 32 attention heads
- Grouped-Query Attention (GQA) with 8 KV heads for memory-efficient inference
- RoPE with adjusted frequency factors for stable 128K context extrapolation
- SwiGLU activation and RMSNorm normalization

**Training Strategy:**
- Pre-trained on over 15 trillion tokens of multilingual web text, code, and curated data
- Aggressive data filtering pipeline: heuristic filters, NSFW classifiers, deduplication, 
  and quality classifiers trained on Llama 2 outputs
- Post-training: multi-round SFT with rejection sampling, followed by DPO
- Iterative alignment: 6 rounds of RLHF with human preference data

**Key Innovation:**
Llama 3.1's strength lies in *massive-scale data curation* and *iterative post-training*. 
The 15T-token pre-training corpus (5× larger than Llama 2) combined with 6 rounds of 
preference optimization yields a model with strong instruction-following and reasoning.
Extended RoPE frequencies enable 128K context without fine-tuning on long documents.

**Strengths for LAMBADA:**
- Largest pre-training corpus among the three → broad vocabulary coverage
- Iterative RLHF gives strong instruction-following for the word-prediction task format
- 128K context window comfortably handles long LAMBADA passages
        """,
        "key_specs": {
            "Parameters": "8B",
            "Layers": "32",
            "Hidden Size": "4096",
            "Attention Heads": "32 (8 KV)",
            "Context Window": "128K tokens",
            "Vocabulary": "128,256 tokens",
            "Training Data": "15T+ tokens",
            "Activation": "SwiGLU",
            "Normalization": "RMSNorm",
            "Positional Encoding": "RoPE (extended)",
        },
    },
}

# ============================================================================
# Benchmark datasets
# ============================================================================
BENCHMARK_FILES = {
    "LAMBADA Test": "_rsc/lambada-dataset/lambada_test_plain_text.txt",
    "LAMBADA Development": "_rsc/lambada-dataset/lambada_development_plain_text.txt",
    "LAMBADA Control": "_rsc/lambada-dataset/lambada_control_test_data_plain_text.txt",
    "Rejected Data": "_rsc/rejected-data1/rejected/rejected_plain_text.txt",
}

BENCHMARK_KEY_MAP = {
    "LAMBADA Test": "lambada_test",
    "LAMBADA Development": "lambada_dev",
    "LAMBADA Control": "lambada_control",
    "Rejected Data": "rejected",
}

# ============================================================================
# Mermaid Diagrams
# ============================================================================
MERMAID_EVALUATION_PIPELINE = """flowchart TD
    A["📂 Load LAMBADA Dataset"] --> B["🎲 Sample N Passages"]
    B --> C["✂️ Extract Target Word\\n(last word of passage)"]
    C --> D["📝 Prepare Prompt\\n(passage without last word)"]
    D --> E{"🤖 Select Model"}
    E --> F["Phi-3 Mini\\n3.8B"]
    E --> G["Gemma 2 9B\\n9B"]
    E --> H["Llama 3.1 8B\\n8B"]
    F --> I["🌐 OpenRouter API"]
    G --> I
    H --> I
    I --> J["📤 Get Prediction"]
    J --> K{"✅ Compare with\\nTarget Word"}
    K -->|Match| L["✔ Correct"]
    K -->|No Match| M["✘ Incorrect"]
    L --> N["📊 Aggregate Metrics"]
    M --> N
    N --> O["💾 Save Results JSON"]
    O --> P["📈 Dashboard Visualization"]"""

MERMAID_LAMBADA_TASK = """flowchart LR
    A["Full Passage\\n'The cat sat on the ___'"] --> B["Split"]
    B --> C["Context:\\n'The cat sat on the'"]
    B --> D["Target:\\n'mat'"]
    C --> E["Send to LLM"]
    E --> F["LLM Predicts:\\n'mat'"]
    F --> G{"Match?"}
    G -->|"prediction == target"| H["✅ Correct"]
    G -->|"prediction != target"| I["❌ Incorrect"]"""

MERMAID_ARCHITECTURE_COMPARISON = """flowchart TB
    subgraph PHI["🔷 Phi-3 Mini — 3.8B"]
        P1["32 Transformer Layers"]
        P2["GQA (32H / 8KV)"]
        P3["SwiGLU Activation"]
        P4["128K Context (RoPE)"]
        P5["Textbook-Quality Data"]
        P1 --> P2 --> P3 --> P4 --> P5
    end
    subgraph GEMMA["🟢 Gemma 2 — 9B"]
        G1["42 Transformer Layers"]
        G2["Local + Global Attention"]
        G3["GeGLU Activation"]
        G4["8K Context (RoPE)"]
        G5["Knowledge Distillation"]
        G1 --> G2 --> G3 --> G4 --> G5
    end
    subgraph LLAMA["🟠 Llama 3.1 — 8B"]
        L1["32 Transformer Layers"]
        L2["GQA (32H / 8KV)"]
        L3["SwiGLU Activation"]
        L4["128K Context (ext. RoPE)"]
        L5["15T Token Pretraining"]
        L1 --> L2 --> L3 --> L4 --> L5
    end"""

MERMAID_PROJECT_WORKFLOW = """flowchart TD
    START(["🚀 Project Start"]) --> DS["📚 LAMBADA Dataset"]
    DS --> PREP["Data Preparation\\n- Load test passages\\n- Sample subset\\n- Extract targets"]
    PREP --> CONFIG["⚙️ Configure Models\\n- Phi-3 Mini\\n- Gemma 2 9B\\n- Llama 3.1 8B"]
    CONFIG --> API["🌐 OpenRouter API\\nSend prompts & collect predictions"]
    API --> EVAL["📊 Evaluation\\n- Accuracy\\n- Latency\\n- Error rate"]
    EVAL --> VIZ["📈 Visualization\\n- Streamlit Dashboard\\n- Comparison charts\\n- Detailed metrics"]
    VIZ --> REPORT["📝 Report Generation\\n- Markdown report\\n- Slide deck\\n- Mermaid diagrams"]
    REPORT --> END(["✅ Complete"])"""

ALL_DIAGRAMS = {
    "Evaluation Pipeline": MERMAID_EVALUATION_PIPELINE,
    "LAMBADA Task Flow": MERMAID_LAMBADA_TASK,
    "Architecture Comparison": MERMAID_ARCHITECTURE_COMPARISON,
    "Project Workflow": MERMAID_PROJECT_WORKFLOW,
}

# ============================================================================
# Demo / fallback results (shown when no real evaluation has been run)
# ============================================================================
DEMO_RESULTS = {
    "phi-3-mini": {
        "lambada_test": {
            "metrics": {
                "model_key": "phi-3-mini", "model_name": "Phi-3 Mini",
                "model_id": "microsoft/phi-3-mini-128k-instruct",
                "provider": "Microsoft", "params": "3.8B",
                "benchmark": "lambada_test", "total_passages": 50,
                "correct": 21, "errors": 0,
                "accuracy": 0.42, "error_rate": 0.0,
                "avg_latency_s": 1.85, "total_time_s": 92.5,
                "timestamp": "2025-12-01T10:00:00",
            },
            "predictions": [],
        },
        "lambada_dev": {
            "metrics": {
                "model_key": "phi-3-mini", "model_name": "Phi-3 Mini",
                "model_id": "microsoft/phi-3-mini-128k-instruct",
                "provider": "Microsoft", "params": "3.8B",
                "benchmark": "lambada_dev", "total_passages": 50,
                "correct": 20, "errors": 0,
                "accuracy": 0.40, "error_rate": 0.0,
                "avg_latency_s": 1.90, "total_time_s": 95.0,
                "timestamp": "2025-12-01T10:05:00",
            },
            "predictions": [],
        },
        "lambada_control": {
            "metrics": {
                "model_key": "phi-3-mini", "model_name": "Phi-3 Mini",
                "model_id": "microsoft/phi-3-mini-128k-instruct",
                "provider": "Microsoft", "params": "3.8B",
                "benchmark": "lambada_control", "total_passages": 50,
                "correct": 14, "errors": 0,
                "accuracy": 0.28, "error_rate": 0.0,
                "avg_latency_s": 1.82, "total_time_s": 91.0,
                "timestamp": "2025-12-01T10:10:00",
            },
            "predictions": [],
        },
        "rejected": {
            "metrics": {
                "model_key": "phi-3-mini", "model_name": "Phi-3 Mini",
                "model_id": "microsoft/phi-3-mini-128k-instruct",
                "provider": "Microsoft", "params": "3.8B",
                "benchmark": "rejected", "total_passages": 50,
                "correct": 9, "errors": 0,
                "accuracy": 0.18, "error_rate": 0.0,
                "avg_latency_s": 1.88, "total_time_s": 94.0,
                "timestamp": "2025-12-01T10:15:00",
            },
            "predictions": [],
        },
    },
    "gemma-2-9b": {
        "lambada_test": {
            "metrics": {
                "model_key": "gemma-2-9b", "model_name": "Gemma 2 9B",
                "model_id": "google/gemma-2-9b-it:free",
                "provider": "Google DeepMind", "params": "9B",
                "benchmark": "lambada_test", "total_passages": 50,
                "correct": 27, "errors": 0,
                "accuracy": 0.54, "error_rate": 0.0,
                "avg_latency_s": 2.10, "total_time_s": 105.0,
                "timestamp": "2025-12-01T11:00:00",
            },
            "predictions": [],
        },
        "lambada_dev": {
            "metrics": {
                "model_key": "gemma-2-9b", "model_name": "Gemma 2 9B",
                "model_id": "google/gemma-2-9b-it:free",
                "provider": "Google DeepMind", "params": "9B",
                "benchmark": "lambada_dev", "total_passages": 50,
                "correct": 25, "errors": 0,
                "accuracy": 0.50, "error_rate": 0.0,
                "avg_latency_s": 2.15, "total_time_s": 107.5,
                "timestamp": "2025-12-01T11:05:00",
            },
            "predictions": [],
        },
        "lambada_control": {
            "metrics": {
                "model_key": "gemma-2-9b", "model_name": "Gemma 2 9B",
                "model_id": "google/gemma-2-9b-it:free",
                "provider": "Google DeepMind", "params": "9B",
                "benchmark": "lambada_control", "total_passages": 50,
                "correct": 18, "errors": 0,
                "accuracy": 0.36, "error_rate": 0.0,
                "avg_latency_s": 2.05, "total_time_s": 102.5,
                "timestamp": "2025-12-01T11:10:00",
            },
            "predictions": [],
        },
        "rejected": {
            "metrics": {
                "model_key": "gemma-2-9b", "model_name": "Gemma 2 9B",
                "model_id": "google/gemma-2-9b-it:free",
                "provider": "Google DeepMind", "params": "9B",
                "benchmark": "rejected", "total_passages": 50,
                "correct": 11, "errors": 0,
                "accuracy": 0.22, "error_rate": 0.0,
                "avg_latency_s": 2.08, "total_time_s": 104.0,
                "timestamp": "2025-12-01T11:15:00",
            },
            "predictions": [],
        },
    },
    "llama-3.1-8b": {
        "lambada_test": {
            "metrics": {
                "model_key": "llama-3.1-8b", "model_name": "Llama 3.1 8B",
                "model_id": "meta-llama/llama-3.1-8b-instruct:free",
                "provider": "Meta", "params": "8B",
                "benchmark": "lambada_test", "total_passages": 50,
                "correct": 30, "errors": 0,
                "accuracy": 0.60, "error_rate": 0.0,
                "avg_latency_s": 1.65, "total_time_s": 82.5,
                "timestamp": "2025-12-01T12:00:00",
            },
            "predictions": [],
        },
        "lambada_dev": {
            "metrics": {
                "model_key": "llama-3.1-8b", "model_name": "Llama 3.1 8B",
                "model_id": "meta-llama/llama-3.1-8b-instruct:free",
                "provider": "Meta", "params": "8B",
                "benchmark": "lambada_dev", "total_passages": 50,
                "correct": 28, "errors": 0,
                "accuracy": 0.56, "error_rate": 0.0,
                "avg_latency_s": 1.70, "total_time_s": 85.0,
                "timestamp": "2025-12-01T12:05:00",
            },
            "predictions": [],
        },
        "lambada_control": {
            "metrics": {
                "model_key": "llama-3.1-8b", "model_name": "Llama 3.1 8B",
                "model_id": "meta-llama/llama-3.1-8b-instruct:free",
                "provider": "Meta", "params": "8B",
                "benchmark": "lambada_control", "total_passages": 50,
                "correct": 19, "errors": 0,
                "accuracy": 0.38, "error_rate": 0.0,
                "avg_latency_s": 1.60, "total_time_s": 80.0,
                "timestamp": "2025-12-01T12:10:00",
            },
            "predictions": [],
        },
        "rejected": {
            "metrics": {
                "model_key": "llama-3.1-8b", "model_name": "Llama 3.1 8B",
                "model_id": "meta-llama/llama-3.1-8b-instruct:free",
                "provider": "Meta", "params": "8B",
                "benchmark": "rejected", "total_passages": 50,
                "correct": 13, "errors": 0,
                "accuracy": 0.26, "error_rate": 0.0,
                "avg_latency_s": 1.62, "total_time_s": 81.0,
                "timestamp": "2025-12-01T12:15:00",
            },
            "predictions": [],
        },
    },
}

# ============================================================================
# Helpers
# ============================================================================

SYSTEM_PROMPT = (
    "You are a language model being evaluated on next-word prediction. "
    "Given a passage with its last word removed, predict the single missing word. "
    "Reply with ONLY that one word — no punctuation, no explanation."
)


def load_passages(file_path, sample_size=50, seed=42):
    with open(file_path, "r", encoding="utf-8") as f:
        passages = [line.strip() for line in f if line.strip()]
    random.seed(seed)
    if len(passages) > sample_size:
        passages = random.sample(passages, sample_size)
    return passages


def extract_target(passage):
    words = passage.split()
    target = words[-1].strip(".,!?;:'\"()[]{}").lower()
    context = " ".join(words[:-1])
    return context, target


def query_openrouter(api_key, model_id, context):
    start = time.time()
    try:
        resp = requests.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": model_id,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {
                        "role": "user",
                        "content": (
                            "Complete this passage with exactly one word. "
                            "Output ONLY the word:\n\n" + context
                        ),
                    },
                ],
                "max_tokens": 10,
                "temperature": 0,
            },
            timeout=60,
        )
        latency = time.time() - start
        if resp.status_code == 200:
            data = resp.json()
            raw = data["choices"][0]["message"]["content"].strip()
            prediction = raw.split()[0] if raw else ""
            prediction = prediction.strip(".,!?;:'\"()[]{}").lower()
            return prediction, latency, None
        return "", latency, f"HTTP {resp.status_code}: {resp.text[:200]}"
    except Exception as exc:
        return "", time.time() - start, str(exc)


def load_saved_results(model_key, benchmark_key):
    path = Path("results") / f"{model_key}_{benchmark_key}.json"
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return None


def get_results(model_key, benchmark_key):
    saved = load_saved_results(model_key, benchmark_key)
    if saved:
        return saved
    if model_key in DEMO_RESULTS and benchmark_key in DEMO_RESULTS[model_key]:
        return DEMO_RESULTS[model_key][benchmark_key]
    return None


def render_mermaid(mermaid_code, height=420):
    html_content = f"""
    <html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
        <style>
            body {{ margin: 0; padding: 10px; background: white; }}
            .mermaid {{ display: flex; justify-content: center; }}
        </style>
    </head>
    <body>
        <pre class="mermaid">
{mermaid_code}
        </pre>
        <script>
            mermaid.initialize({{ startOnLoad: true, theme: 'default', securityLevel: 'loose' }});
        </script>
    </body>
    </html>
    """
    components.html(html_content, height=height, scrolling=True)


def save_mermaid_png(mermaid_code, output_path):
    """Save mermaid diagram as PNG via mermaid.ink service."""
    try:
        encoded = base64.urlsafe_b64encode(mermaid_code.encode("utf-8")).decode("utf-8")
        url = f"https://mermaid.ink/img/{encoded}"
        resp = requests.get(url, timeout=15)
        if resp.status_code == 200:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "wb") as f:
                f.write(resp.content)
            return True
    except Exception:
        pass
    return False


# ============================================================================
# Sidebar
# ============================================================================
with st.sidebar:
    st.image(
        "https://img.icons8.com/fluency/96/brain.png",
        width=60,
    )
    st.title("LAMBADA Evaluator")
    st.markdown("---")

    api_key = st.text_input(
        "OpenRouter API Key",
        type="password",
        help="Required to run live evaluations. Get one at https://openrouter.ai/keys",
    )

    st.markdown("---")
    selected_model_name = st.selectbox(
        "Select LLM",
        options=[MODELS[k]["name"] for k in MODEL_KEYS],
        index=0,
    )
    selected_model_key = [k for k, v in MODELS.items() if v["name"] == selected_model_name][0]

    selected_benchmark = st.selectbox(
        "Select Benchmark",
        options=list(BENCHMARK_FILES.keys()),
        index=0,
    )

    sample_size = st.slider("Sample Size", 10, 200, 50, 10)

    st.markdown("---")
    st.caption("Models: Phi-3 Mini | Gemma 2 9B | Llama 3.1 8B")
    st.caption("API: OpenRouter")

# ============================================================================
# Tabs
# ============================================================================
tab_overview, tab_llm, tab_eval, tab_compare, tab_workflow, tab_data = st.tabs(
    ["Overview", "LLM Profiles", "Evaluation", "Comparison", "Workflow", "Dataset Explorer"]
)

# ============================================================================
# Tab 1: Overview
# ============================================================================
with tab_overview:
    st.header("LAMBADA SLM Evaluation Dashboard")
    st.markdown("""
    This dashboard evaluates **three Small Language Models (SLMs)** on the
    **LAMBADA benchmark** — a challenging word-prediction task that requires
    understanding long-range dependencies in narrative text.
    """)

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Models Evaluated", "3 SLMs")
    with col2:
        st.metric("Benchmark", "LAMBADA")
    with col3:
        st.metric("Test Passages", "5,153")

    st.markdown("### About LAMBADA")
    st.markdown("""
    The **LAMBADA** (LAnguage Modeling Broadened to Account for Discourse Aspects)
    dataset evaluates language models on **last-word prediction** in narrative passages.

    - Passages are extracted from novels (BookCorpus)
    - Humans can guess the last word when seeing the full passage, but **not** from the
      last sentence alone
    - Models must understand **broad discourse context** — not just local patterns

    | Split       | Passages | Source       |
    |-------------|----------|--------------|
    | Train       | 2,662    | Full novels  |
    | Development | 4,869    | Filtered     |
    | Test        | 5,153    | Filtered     |
    | Control     | 5,153    | Unfiltered   |
    """)

    st.markdown("### Models Under Evaluation")
    cols = st.columns(3)
    for i, mk in enumerate(MODEL_KEYS):
        m = MODELS[mk]
        with cols[i]:
            st.markdown(f"""
            <div style="padding:15px; border-radius:10px; border:2px solid {m['color']}; text-align:center;">
                <h4 style="color:{m['color']}">{m['name']}</h4>
                <p><b>{m['provider']}</b></p>
                <p>{m['params']} parameters</p>
                <p>{m['context_window']} context</p>
            </div>
            """, unsafe_allow_html=True)

# ============================================================================
# Tab 2: LLM Profiles
# ============================================================================
with tab_llm:
    st.header(f"LLM Profile: {selected_model_name}")

    detail = LLM_DETAILS[selected_model_key]
    st.subheader(detail["title"])
    st.markdown(detail["overview"])

    col_left, col_right = st.columns([3, 2])

    with col_left:
        st.markdown("### Working Principle")
        st.markdown(detail["working_principle"])

    with col_right:
        st.markdown("### Key Specifications")
        specs_df = pd.DataFrame(
            list(detail["key_specs"].items()),
            columns=["Specification", "Value"],
        )
        st.dataframe(specs_df, use_container_width=True, hide_index=True)

    st.markdown("---")
    st.markdown("### All Models — Specification Comparison")
    comparison_data = []
    for mk in MODEL_KEYS:
        row = {"Model": MODELS[mk]["name"]}
        row.update(LLM_DETAILS[mk]["key_specs"])
        comparison_data.append(row)
    comp_df = pd.DataFrame(comparison_data)
    st.dataframe(comp_df, use_container_width=True, hide_index=True)

# ============================================================================
# Tab 3: Evaluation
# ============================================================================
with tab_eval:
    st.header("Run Evaluation")

    bench_key = BENCHMARK_KEY_MAP[selected_benchmark]

    existing = get_results(selected_model_key, bench_key)
    is_demo = load_saved_results(selected_model_key, bench_key) is None

    st.info(
        f"**Model:** {selected_model_name}  |  "
        f"**Benchmark:** {selected_benchmark}  |  "
        f"**Sample Size:** {sample_size}"
    )

    if st.button("Run Live Evaluation", type="primary", disabled=not api_key):
        if not api_key:
            st.error("Please enter your OpenRouter API key in the sidebar.")
        else:
            bench_file = BENCHMARK_FILES[selected_benchmark]
            if not Path(bench_file).exists():
                st.error(f"Dataset file not found: {bench_file}")
            else:
                passages = load_passages(bench_file, sample_size)
                st.write(f"Loaded {len(passages)} passages.")

                progress_bar = st.progress(0.0)
                status_text = st.empty()
                results_container = st.empty()

                info = MODELS[selected_model_key]
                preds = []
                correct = 0
                errors_count = 0
                total_latency = 0.0

                for i, passage in enumerate(passages):
                    ctx, tgt = extract_target(passage)
                    pred, lat, err = query_openrouter(api_key, info["id"], ctx)

                    is_correct = pred == tgt
                    if is_correct:
                        correct += 1
                    if err:
                        errors_count += 1
                    total_latency += lat

                    preds.append({
                        "idx": i, "context_snippet": ctx[:300],
                        "target": tgt, "prediction": pred,
                        "correct": is_correct, "latency_s": round(lat, 3),
                        "error": err,
                    })

                    frac = (i + 1) / len(passages)
                    progress_bar.progress(frac)
                    status_text.text(
                        f"Passage {i+1}/{len(passages)} — "
                        f"Acc: {correct/(i+1):.1%} — "
                        f"Pred: '{pred}' | Target: '{tgt}'"
                    )
                    time.sleep(0.3)

                n = len(passages)
                metrics = {
                    "model_key": selected_model_key,
                    "model_name": info["name"],
                    "model_id": info["id"],
                    "provider": info["provider"],
                    "params": info["params"],
                    "benchmark": bench_key,
                    "total_passages": n,
                    "correct": correct,
                    "errors": errors_count,
                    "accuracy": round(correct / n, 4) if n else 0,
                    "error_rate": round(errors_count / n, 4) if n else 0,
                    "avg_latency_s": round(total_latency / n, 3) if n else 0,
                    "total_time_s": round(total_latency, 2),
                    "timestamp": datetime.now().isoformat(),
                }

                Path("results").mkdir(exist_ok=True)
                fpath = Path("results") / f"{selected_model_key}_{bench_key}.json"
                with open(fpath, "w", encoding="utf-8") as f:
                    json.dump({"metrics": metrics, "predictions": preds}, f, indent=2)

                st.success(f"Evaluation complete! Accuracy: {metrics['accuracy']:.1%}")
                existing = {"metrics": metrics, "predictions": preds}
                is_demo = False

    st.markdown("---")

    if existing:
        m = existing["metrics"]
        label = " *(demo data — run evaluation for real results)*" if is_demo else ""
        st.subheader(f"Results: {m['model_name']} on {selected_benchmark}{label}")

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Accuracy", f"{m['accuracy']:.1%}")
        c2.metric("Correct / Total", f"{m['correct']} / {m['total_passages']}")
        c3.metric("Avg Latency", f"{m['avg_latency_s']:.2f}s")
        c4.metric("Error Rate", f"{m['error_rate']:.1%}")

        if existing.get("predictions"):
            st.markdown("#### Per-Passage Predictions")
            pred_df = pd.DataFrame(existing["predictions"])
            display_cols = ["idx", "target", "prediction", "correct", "latency_s"]
            available_cols = [c for c in display_cols if c in pred_df.columns]
            st.dataframe(pred_df[available_cols], use_container_width=True, hide_index=True)
    else:
        st.warning("No results available. Run an evaluation or check that demo data is loaded.")

# ============================================================================
# Tab 4: Comparison
# ============================================================================
with tab_compare:
    st.header("Model Comparison")

    bench_choice = st.selectbox(
        "Benchmark for Comparison",
        options=list(BENCHMARK_FILES.keys()),
        index=0,
        key="compare_bench",
    )
    bench_k = BENCHMARK_KEY_MAP[bench_choice]

    all_metrics = []
    for mk in MODEL_KEYS:
        res = get_results(mk, bench_k)
        if res:
            all_metrics.append(res["metrics"])

    if all_metrics:
        st.subheader(f"Comparison on {bench_choice}")

        comp_data = []
        for m in all_metrics:
            comp_data.append({
                "Model": m["model_name"],
                "Provider": m["provider"],
                "Parameters": m["params"],
                "Accuracy": f"{m['accuracy']:.1%}",
                "Correct": m["correct"],
                "Total": m["total_passages"],
                "Avg Latency (s)": m["avg_latency_s"],
                "Error Rate": f"{m['error_rate']:.1%}",
            })
        st.dataframe(pd.DataFrame(comp_data), use_container_width=True, hide_index=True)

        st.markdown("---")

        col_a, col_b = st.columns(2)
        with col_a:
            st.markdown("#### Accuracy Comparison")
            fig_acc = go.Figure()
            for m in all_metrics:
                color = MODELS[m["model_key"]]["color"]
                fig_acc.add_trace(go.Bar(
                    x=[m["model_name"]],
                    y=[m["accuracy"] * 100],
                    marker_color=color,
                    name=m["model_name"],
                    text=[f"{m['accuracy']:.1%}"],
                    textposition="outside",
                ))
            fig_acc.update_layout(
                yaxis_title="Accuracy (%)", showlegend=False,
                yaxis=dict(range=[0, 100]),
                height=400,
            )
            st.plotly_chart(fig_acc, use_container_width=True)

        with col_b:
            st.markdown("#### Latency Comparison")
            fig_lat = go.Figure()
            for m in all_metrics:
                color = MODELS[m["model_key"]]["color"]
                fig_lat.add_trace(go.Bar(
                    x=[m["model_name"]],
                    y=[m["avg_latency_s"]],
                    marker_color=color,
                    name=m["model_name"],
                    text=[f"{m['avg_latency_s']:.2f}s"],
                    textposition="outside",
                ))
            fig_lat.update_layout(
                yaxis_title="Avg Latency (seconds)", showlegend=False,
                height=400,
            )
            st.plotly_chart(fig_lat, use_container_width=True)

        st.markdown("---")
        st.markdown("#### Cross-Benchmark Comparison")
        cross_data = []
        for mk in MODEL_KEYS:
            for bn, bk in BENCHMARK_KEY_MAP.items():
                res = get_results(mk, bk)
                if res:
                    cross_data.append({
                        "Model": res["metrics"]["model_name"],
                        "Benchmark": bn,
                        "Accuracy": res["metrics"]["accuracy"] * 100,
                        "Latency": res["metrics"]["avg_latency_s"],
                    })

        if cross_data:
            cross_df = pd.DataFrame(cross_data)
            fig_cross = px.bar(
                cross_df, x="Benchmark", y="Accuracy", color="Model",
                barmode="group",
                color_discrete_map={
                    "Phi-3 Mini": "#2196F3",
                    "Gemma 2 9B": "#4CAF50",
                    "Llama 3.1 8B": "#FF9800",
                },
                labels={"Accuracy": "Accuracy (%)"},
                height=450,
            )
            st.plotly_chart(fig_cross, use_container_width=True)

            st.markdown("#### Full Metrics Table")
            full_table = []
            for mk in MODEL_KEYS:
                row = {"Model": MODELS[mk]["name"]}
                for bn, bk in BENCHMARK_KEY_MAP.items():
                    res = get_results(mk, bk)
                    if res:
                        row[f"{bn} Acc"] = f"{res['metrics']['accuracy']:.1%}"
                        row[f"{bn} Lat(s)"] = res["metrics"]["avg_latency_s"]
                full_table.append(row)
            st.dataframe(pd.DataFrame(full_table), use_container_width=True, hide_index=True)
    else:
        st.warning("No results available for this benchmark. Run evaluations first.")

# ============================================================================
# Tab 5: Workflow Diagrams
# ============================================================================
with tab_workflow:
    st.header("Workflow & Architecture Diagrams")

    diagram_choice = st.selectbox(
        "Select Diagram",
        options=list(ALL_DIAGRAMS.keys()),
    )

    mermaid_code = ALL_DIAGRAMS[diagram_choice]

    st.markdown(f"### {diagram_choice}")
    render_mermaid(mermaid_code, height=500)

    with st.expander("View Mermaid Source Code"):
        st.code(mermaid_code, language="text")

    st.markdown("---")
    col_save, col_status = st.columns([1, 3])
    with col_save:
        if st.button("Save All Diagrams as PNG"):
            saved = []
            for name, code in ALL_DIAGRAMS.items():
                fname = name.lower().replace(" ", "_") + ".png"
                fpath = f"diagrams/{fname}"
                if save_mermaid_png(code, fpath):
                    saved.append(fname)
            with col_status:
                if saved:
                    st.success(f"Saved {len(saved)} diagrams to `diagrams/` folder")
                else:
                    st.error(
                        "Could not save PNGs. "
                        "Check internet connectivity (uses mermaid.ink service)."
                    )

    st.markdown("---")
    st.markdown("### All Diagrams Preview")
    for name, code in ALL_DIAGRAMS.items():
        with st.expander(name):
            render_mermaid(code, height=400)

# ============================================================================
# Tab 6: Dataset Explorer
# ============================================================================
with tab_data:
    st.header("Dataset Explorer")

    dataset_choice = st.selectbox(
        "Select Dataset",
        options=list(BENCHMARK_FILES.keys()),
        key="data_explorer",
    )

    file_path = BENCHMARK_FILES[dataset_choice]
    if Path(file_path).exists():
        with open(file_path, "r", encoding="utf-8") as f:
            all_lines = [line.strip() for line in f if line.strip()]

        st.metric("Total Passages", len(all_lines))

        num_display = st.slider(
            "Passages to display", 5, min(100, len(all_lines)), 10, key="n_display"
        )

        st.markdown("---")
        for i, passage in enumerate(all_lines[:num_display]):
            words = passage.split()
            target_word = words[-1]
            context = " ".join(words[:-1])

            with st.expander(f"Passage {i+1} — Target: **{target_word}**"):
                st.markdown(f"**Context:** {context}")
                st.markdown(f"**Target word:** `{target_word}`")
                st.markdown(f"**Length:** {len(words)} words")
    else:
        st.error(f"File not found: {file_path}")

    st.markdown("---")
    st.markdown("### Dataset Statistics")
    stats_data = []
    for name, fpath in BENCHMARK_FILES.items():
        if Path(fpath).exists():
            with open(fpath, "r", encoding="utf-8") as f:
                lines = [l.strip() for l in f if l.strip()]
            avg_len = sum(len(l.split()) for l in lines) / len(lines) if lines else 0
            stats_data.append({
                "Dataset": name,
                "Passages": len(lines),
                "Avg Words/Passage": round(avg_len, 1),
            })
    if stats_data:
        st.dataframe(pd.DataFrame(stats_data), use_container_width=True, hide_index=True)
